### ISSUE TITLE
Error "Expected group with children" in h5 

### ISSUE THREAD

**Issue by akademy** [silx-kit/h5whale#1]
Keep getting the error "Expected group with children" which ever nx file I use (eg data/nexus.nx ).

To get it to build the Dockerfile I had to change line 13 to:

`RUN npm install -g pnpm@8.15.8`

The docker-compose.yaml file then runs fine, but h5web only returns the above error when you provide a file in the url.

**Comment by axelboc** [comment]
Sorry, this project was quite out of date! I've opened a PR to update everything. Thanks for the report!

**Comment by akademy** [comment]
Thanks for taking a look.
